### ISSUE TITLE
Debugging with Visual Studio

### ISSUE THREAD

**Issue by timsdesigns** [timsdesigns/GLTF-Export#2]
The Plugin doesn't load for debugging:
 - Issue to reproduce:
   - `GrasshopperDeveloperOptions` > Add Assembly > `.\GH-Helper\Web_Exporter\GLTF-Export\bin\Debug\net7.0`
   - Start debug Session from within Visual Studio
   - hit space bar and type `Gltf Exporter` or `gltfExp`
   - the component doesn't show up
 - Workaround:
   - drag and drop the latest `.gha` from bin onto canvas during debug session
 - Possible Causes:
   - the postbuilt event in the **`.\Web_Exporter.csproj`** under `Target`
     (added because according to MS the `<TargetExt>.gha</TargetExt>` isn't supported in .net7 anymore) is:
     - renaming the .dll after the debugger starts rhino/grasshopper
     - causing some other issue
   - my machine has issues with loading Assemblies through GrasshopperDeveloperOptions
   - some other Rhino8 or .net7 related problem

**Comment by timsdesigns** [comment]
![image](https://github.com/timsdesigns/GLTF-Export/assets/10819086/ce768782-3caf-4a8d-93d7-ab4377b838ff)

**Comment by timsdesigns** [comment]
![image](https://github.com/timsdesigns/GLTF-Export/assets/10819086/c9bc6fb1-5406-4fe5-92d9-aa4b9e5669aa)

**Comment by lin-ycv** [comment]
>`<TargetExt>.gha</TargetExt>` isn't supported in .net7 anymore

not sure where you read this, but it is working, should be able to debug in VS now

**Comment by timsdesigns** [comment]
Awesome!
